# Generated by Django 5.2.8 on 2025-11-25 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_bill_savingsgoal_goalcontribution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('savings_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('budget_adherence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('emergency_fund_months', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('bill_reminder', 'Bill Reminder'), ('goal_milestone', 'Goal Milestone'), ('unusual_spending', 'Unusual Spending'), ('monthly_summary', 'Monthly Summary')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('budget_alerts', models.BooleanField(default=True)),
                ('bill_reminders', models.BooleanField(default=True)),
                ('monthly_reports', models.BooleanField(default=True)),
                ('goal_notifications', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=20)),
                ('number_format', models.CharField(default='en-US', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('50_percent', '50% Budget Used'), ('75_percent', '75% Budget Used'), ('90_percent', '90% Budget Used'), ('100_percent', 'Budget Exceeded')], max_length=15)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.budget')),
            ],
            options={
                'unique_together': {('budget', 'alert_type')},
            },
        ),
    ]
